### ISSUE TITLE
配置好之后,idea打不开了,双击没反应

### ISSUE THREAD

**Issue by remxme** [pengzhile/jetbrains-agent#1]
配置好之后,idea打不开了,双击没反应

**Comment by pengzhile** [comment]
看一下你的vmoptions呢

**Comment by pengzhile** [comment]
出现这种情况多半是你下载下来的jetbrains-agent.jar文件地址与你vmoptions里配置的不一致，你可以检查一下。

**Comment by remxme** [comment]
搞定了, 开始jar没下载对,
注册后, 那行是不是可以删掉了?

**Comment by pengzhile** [comment]
不要删除。

**Comment by CharkeyQK** [comment]
Q: 注册后, 那行是不是可以删掉了?
A: No
