### ISSUE TITLE
Mac版phpstorm2018.2.1都没有注册哪来help菜单😂

### ISSUE THREAD

**Issue by xiebruce** [pengzhile/jetbrains-agent#2]
![snip20180817_2](https://user-images.githubusercontent.com/13575500/44258624-04fc8780-a242-11e8-929c-109902eddb3f.png)
如图，都没有注册，哪有Help菜单啊😂

**Comment by xiebruce** [comment]
@pengzhile 呃。。。我怎么没想到呢？哈哈，谢啦！顺便问一下，2018.2.1以后，以前的IntelliJIDEALicenseServer是不是不能用了？我以前都是用自己搭的那个服务器

**Comment by pengzhile** [comment]
是的，注册服务器大改。之前在lanyus评论过新服务器的逻辑，看没人动索性自己来做了一套。

**Comment by xiebruce** [comment]
@pengzhile 有个问题，因为选择了试用，好像现在直接去注册没法注册，因为已经Licensed to Phpstorm Evaluator 了，是不是要等过期之后才能再试了？
![snip20180817_7](https://user-images.githubusercontent.com/13575500/44259641-ac7ab980-a244-11e8-8f24-c87e5dd82ea3.png)

**Comment by pengzhile** [comment]
不用，可在Help菜单选择Register...选择license server来重新注册。

**Comment by xiebruce** [comment]
我这个截图，就是你说的这个步骤呀，但是没用啊，圈圈转完就停在这个界面了，没什么提示，看about还是Licensed to Phpstorm Evaluator 
![image](https://user-images.githubusercontent.com/13575500/44260062-ee582f80-a245-11e8-9ba7-d2580e3ecef2.png)

**Comment by pengzhile** [comment]
你这域名是17个字符。

**Comment by xiebruce** [comment]
16个也不行啊，我试了
![image](https://user-images.githubusercontent.com/13575500/44263093-27959d00-a250-11e8-8e2c-0e0106310312.png)
![image](https://user-images.githubusercontent.com/13575500/44263110-409e4e00-a250-11e8-937f-c4ca9b09ff36.png)

**Comment by xiebruce** [comment]
哥们我把你给坑惨了，我用的是这玩意：JetbrainsCrack-3.1-release-enc.jar，我说怎么不可以的，我下载你的就可以了，谢谢了！

**Comment by pengzhile** [comment]
好吧。
