### ISSUE TITLE
不知那个域名怎么弄

### ISSUE THREAD

**Issue by newcaptain** [pengzhile/jetbrains-agent#4]
随便弄了个16字符的域名
一直报 connection timed out

**Comment by piaoyizy** [comment]
我按教程来也没激活成功。求告知方法，谢谢！
![cf18defc-7ebb-4b21-a96f-05201c15acdb](https://user-images.githubusercontent.com/26868640/44306574-3c933d00-a3c4-11e8-9a50-15edad256887.png)

**Comment by pengzhile** [comment]
@piaoyizy 你设置完vmoptions之后重启IDE了吗？

**Comment by pengzhile** [comment]
@piaoyizy 还有域名总共16个字符。

**Comment by pengzhile** [comment]
比如http://idea.abcdefg.com

**Comment by newcaptain** [comment]
解决了， 应该是域名没弄对

**Comment by piaoyizy** [comment]
@pengzhile   谢谢，成功了， 我以为域名字符超过16个都可以，就乱打了一些长的。
