### ISSUE TITLE
设置过后，idea都打不开

### ISSUE THREAD

**Issue by noroadzh** [pengzhile/jetbrains-agent#7]
图片怎么发呢。。。。

![1](https://user-images.githubusercontent.com/1166241/44321565-55125e80-a47b-11e8-8121-112d2f4c72e8.png)
![2](https://user-images.githubusercontent.com/1166241/44321567-5774b880-a47b-11e8-8bd6-6472b1d6e93e.png)

**Comment by noroadzh** [comment]
我的操作系统是 win10，idea用的是2018.2.1

**Comment by pengzhile** [comment]
截图后直接在这里的文本框粘贴。

**Comment by noroadzh** [comment]
成功了，多谢了，你最好在releases 里面放下 下载

**Comment by pengzhile** [comment]
谢谢提醒，我已release了一个版本。
