### ISSUE TITLE
webstorm,goland提示validation failed

### ISSUE THREAD

**Issue by hanguatest** [pengzhile/jetbrains-agent#8]
webstorm,goland提示key is invalid，
相同配置的idea可以按照教程激活。

**Comment by pengzhile** [comment]
请截图一下webstorm, goland的vmoptions以及激活界面。

**Comment by hanguatest** [comment]
以下是webstorm的：
![image](https://user-images.githubusercontent.com/42526970/44327608-ad545b00-a491-11e8-8f67-34bf4fa1fa0c.png)

![image](https://user-images.githubusercontent.com/42526970/44327656-d70d8200-a491-11e8-8a48-bd430d6c3c4b.png)

**Comment by pengzhile** [comment]
IDE重启了吗？这种情况是你这份vmoptions没有生效，你的vmoptions是从哪里编辑的？编辑之后是否保存后重启IDE？

**Comment by hanguatest** [comment]
我使用的是Toolbox，通过下图的按钮编辑vmoptions的，
![image](https://user-images.githubusercontent.com/42526970/44329222-7765a580-a496-11e8-9794-a85d645dabb7.png)
`Intellij IDEA`可以正常激活，`Goland`, `Webstorm`不可以。

**Comment by pengzhile** [comment]
试试分别从GoLand、WebStorm的Help菜单修改vmoptions看能否激活。

**Comment by hanguatest** [comment]
菜单中是正确的。
原因可能是Jenbrains对不同IDE加载vmoptions的策略不同。

**Comment by pengzhile** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/343491/44329956-65850200-a498-11e8-8a3f-304040cf40d5.png">

我看你的截图好像是在编辑IDEA的vmoptions，对其他IDE应该没效果吧。

**Comment by hanguatest** [comment]
我只截了idea的，goland, webstorm没截
