### ISSUE TITLE
提示read time out

### ISSUE THREAD

**Issue by DimplePhoenix** [pengzhile/jetbrains-agent#9]
![image](https://user-images.githubusercontent.com/14941270/44439833-00482280-a5f8-11e8-9e5b-e1a2d5c21abe.png)
隔一段时间就会出现

**Comment by pengzhile** [comment]
因为license server方式需要联网，这种情况是你那边网络不通畅。我这边也会调大ticket的有效期，规避网络状态不好的问题。

**Comment by DimplePhoenix** [comment]
但用你演示的http://idea.abcdefg.com则未发现以上问题。（同样的网络环境）

**Comment by pengzhile** [comment]
新release的包同时支持注册码激活了，如果你网路不佳，可以试试这种方式。
